### ISSUE TITLE
authenticateUser  の出力について

### ISSUE THREAD

**Issue by launcelot777** [Netkoubou/alice#1]
authenticateUser  の出力に関してです。
permission が、　`privilige'　等になっていますが、　 status では、SUCCESSのように大文字になっています。
定数だと思いますので大文字にするのが通常だと思いますが、何か意味合いがあるのでしょうか？

**Comment by sarunokoshikake0831** [comment]
確かに、言われてみればそうです。
と言うか、何故そうしなかったのだろう ... ?

直しておきます。

**Comment by sarunokoshikake0831** [comment]
訂正しました。
また、文字列であることを明示するために、シングルクォートで囲んでみました。
如何でしょう?

**Comment by launcelot777** [comment]
確認しました。
ここの機能は便利ですね。
