### ISSUE TITLE
ユーザ管理テーブルについて

### ISSUE THREAD

**Issue by launcelot777** [Netkoubou/alice#12]
現在の構成だと、冗長性があり、その分コーディングがややこしくなりそうです。
次のようにテーブル分割（正規化）してはどうでしょうか？

-------- 現状 ----------
[ユーザ管理テーブル]
ユーザID（PK)、部門診療科コード（PK)
アカウント
パスワード
各権限
電話番号
FAX番号
メールアドレス
等々
↓
------------ 案 ---------------
[ユーザ管理テーブル]
ユーザID（PK)
アカウント
パスワード
電話番号
FAX番号
メールアドレス
等々

[ユーザ・権限管理テーブル]
ユーザID（PK)、部門診療科コード（PK)
各権限
等々

レコードの数が少ないので、結合時にほとんど処理は重くならないと思われます。
いかがでしょうか。

**Comment by sarunokoshikake0831** [comment]
DBに取り込み済み
