### ISSUE TITLE
発注について

### ISSUE THREAD

**Issue by launcelot777** [Netkoubou/alice#13]
１．商品A、Bを発注
２．商品Aのみ納品済みになった
３．同じ発注書で商品Aを再度追加発注
といったケースは考えられるのでしょうか？

**Comment by sarunokoshikake0831** [comment]
現状の UI ではそのケースに対応できるようにしています。
理由は以下です。
- そういうケースは (滅多にないかもしれないが) あってもおかしくなさそう
- そのケースをわざわざ禁止する理由が特に見当たらない
- コード上、それをできないようにすることが面倒

**Comment by sarunokoshikake0831** [comment]
DB上、それを許容することはできないため、同一発注の中で物品が複数回現れることは不可。
