### ISSUE TITLE
発注について②

### ISSUE THREAD

**Issue by launcelot777** [Netkoubou/alice#14]
ある発注において
１．品名Aを３個発注
２．その後、品名Aを５個追加
本来は、品名Aの個数を８個にすればいいが、
オペレーターが間違えて
品名A　３個
品名A　５個
のように同一品名が複数レコードにわたるケースはありうるのでしょうか？
チェックが走って「すでに同じ品名が発注書にあります」などのエラーに
なる仕様でしょうか？

**Comment by sarunokoshikake0831** [comment]
現状、エラーにしない仕様としています。
理由は、(村さんが既に書いてますが) 「既に A を 3 個発注した (そして発注済みにした) のだけれど、
3 個じゃ足りないことが判明したので、後で 5 個追加」
のようなケースにも対応できるようにです。

それをできないようにしても、業務に携わる人にとってはさほど嬉しくないのではないかなぁ、と。
我々にとっても、勿論嬉しくないですし (正直、チェックが面倒 ...)。

**Comment by sarunokoshikake0831** [comment]
前のissue と同じ。
