### ISSUE TITLE
起案番号について

### ISSUE THREAD

**Issue by launcelot777** [Netkoubou/alice#16]
起案番号のフォーマットについて。

案１．2015-外科-0001　　（年度-部門診療科略称-年度・部門診療科ごとの連番）
案２．外科-0001-2015
案３．クライアントーサーバ間で送受信するデータは上記どちらか。表示するときに、外科-0001　等にする。

どういたしましょうか？

**Comment by sarunokoshikake0831** [comment]
略称-yyyy-xxxx とします。これをクライアント-サーバ間でやりとりする。
