### ISSUE TITLE
仕様の細かいところ

### ISSUE THREAD

**Issue by launcelot777** [Netkoubou/alice#17]
例えば、ユーザ、ユーザの権限を登録後、ユーザ権限を全て削除してしまった時。
同様に、発注、発注詳細を登録後、発注詳細をすべて削除されてしまった時。

どの部門にも所属していない、何の権限もないユーザや、発注する製品のない発注を、どう扱うか。
基本的には削除されるべきだと思っています。

少なくとも発注部品のない発注書が承認権限者のところに回されるのは仕様バグかとも思えますが、
意外と何か特別な形で使用している可能性もあります。

一度議論しておきませんか。

**Comment by sarunokoshikake0831** [comment]
Wiki には明記していないのですが (すいません)、
- UI 側で、物品が 1 個以上登録されている発注のみ、registerOrder を発行できるようにしています。
  つまり、物品が 0 個の発注を登録することはできません。
- UI 側で、(既に登録した発注から物品を削除しまくって) 物品を 0 個にした発注は、eraseOrder しかできないようにしています。つまり、物品が 0 個の発注が updateOrder されることはありません (UI がバグってなければ)

この仕様で良いのか、確認の意も含めて、議論しましょう (ユーザ権限の話しも含めて)。

**Comment by sarunokoshikake0831** [comment]
UI側で、かならずどこかしらの部門診療科に所属するよう、制限をかける予定です。
但し、なんの権限もないユーザは存在できるようにしてほしい、との要望があったので、
それは許すようにします。
そんなユーザは、発注はできませんが、経費の入力だけできます。
