### ISSUE TITLE
Server API registerOrder の入力 originator について

### ISSUE THREAD

**Issue by sarunokoshikake0831** [Netkoubou/alice#2]
新規に作成した発注の起案者 (originator) がログインしているユーザであることは自明なので、
入力から削除しようと考えています。
問題ないでしょうか?

**Comment by launcelot777** [comment]
運用状態がよくわかっていないのですが・・・
例えば、Aさんがログイン→PC操作後、ログアウトせずに離席→BさんがPC席にきて発注　なんて流れもあるんですか？？？もし、頻繁にあるようならログインユーザと発注者が一致しなくなっちゃいますね。

**Comment by sarunokoshikake0831** [comment]
アカウントは個人に割り当てる (共有アカウントはない) ので、その流れはありえない、
と考えています。
B さんが発注する場合、B さんは別の計算機で別途ログインする必要があります。
このご時世、一人 1 PC はあたり前なので、PC の共有はしない、
という運用を強制する方針で問題ないと思いますが、いかがでしょう?

**Comment by launcelot777** [comment]
了解しました。
それでいいと思います。それでいきましょう！

**Comment by sarunokoshikake0831** [comment]
すいません、了解を得る前に Wiki から消してました。。。
とりあえず close します。
