### ISSUE TITLE
納品書の合計額を出す処理について

### ISSUE THREAD

**Issue by launcelot777** [Netkoubou/alice#21]
月ごと、診療科ごとの納品書合計額を算出する仕組みについてですが、以下提案です。

〇まず、購入金額（請求金額？）合計テーブルを作る
　PrimaryKeyは、nendo, month, department_cd
　予算管理画面や、予算管理グラフは、このテーブルから値をとってくれば良い。

〇このテーブルにデータがはいるタイミング
予算管理画面に「先月の物品購入（請求）額の集計をしますか？」といったボタンを作る。未集計なら集計ロジックが走る。集計済みなら「再集計しますか？」と確認。イエスなら、対象月の発注テーブルから金額を合算。

〇納品時処理の確認
発注書の購入（請求）金額   →  発注テーブルの購入（請求）金額に入る
個々の物品の納品単価　    →  発注詳細テーブルの納品単価と製品テーブルの単価に値が入る。（プラス最高・最低単価との比較も行う）

※月次処理の計算対象は、「発注月」で見るんでしたっけ？「納品月」でしたっけ？

**Comment by sarunokoshikake0831** [comment]
- 合計テーブルは作らず、その都度計算するようにする。
- テーブルは作らないです。
- updateOrder 発行時に毎回それらを確定する。

発注が完了した日を、全物品の納品日とします (last_modified_date がその納品日)。
