### ISSUE TITLE
エラーコードについて

### ISSUE THREAD

**Issue by launcelot777** [Netkoubou/alice#24]
サーバー側でエラーがあった時、ログを出力するようにしているのですが、ログ出力に失敗したとき（めったにないエラーだと思いますが・・・）の処理もプログラムに書かなければなりません。
このエラーの時はログ出力されないため、何が起こったのかわからなくなると思います。
それなので、「ログ出力エラー」であることをクライアント側に通知して、エラーの理由をわかるようにしたいのですが、いかがでしょうか。

返信のステータスは、今のところ 0,1,255 以外はあいていると思うので、254 を使ってもいいでしょうか。

**Comment by sarunokoshikake0831** [comment]
その場合は、異常終了することになりました。
クライアントに 255 を返し、exit ステータス 0 以外で異常終了します。
