### ISSUE TITLE
Server API registerOrder の入力 department 及び trader について

### ISSUE THREAD

**Issue by sarunokoshikake0831** [Netkoubou/alice#3]
それぞれ、表示用の名前 (name) ではなく、内部的な ID であることを明示するために、
- department_code
- trader_code

という名前にしようと考えています。
如何でしょうか?

**Comment by launcelot777** [comment]
わかりやすくていいと思います。
キャメル記法かスネーク記法か　( departmentCode か department_code か)、
このようなケースだとどっちが一般的かわかりませんのでおまかせします。

**Comment by sarunokoshikake0831** [comment]
ありがとうございます。

API 名でキャメルケースを使っているので、
JSON の鍵はスネーク記法 (って言うんですね、知りませんでした) で行くことにしました。

Wiki は訂正したので、close します。
