### ISSUE TITLE
エラーコードについて

### ISSUE THREAD

**Issue by launcelot777** [Netkoubou/alice#4]
現状、エラーコード設計がなされていないと思います。（私が知らないだけかもしれませんが・・・）
例えば、ログイン時のエラーでも、ユーザ名とパスワードが一致しなかった、とかDB接続に失敗した、とか色々あると思います。
すぐにではなくてもいいかもしれませんが、将来的には、エラーコードが〇〇番だから、ソースコードのあそこでエラーになったはず、というようにわかるようにしておくべきかと思いますがいかがでしょうか。

**Comment by sarunokoshikake0831** [comment]
確かに、してないです。。。
Server API の出力 (返り値) を以下のような構造にして、
サーバのエラーをユーザに通知できるようにする、
というのはどうでしょう?

```
{
    STATUS_CODE: Int,        // 0 は成功、1 - 1023 は警告、1024 以上はエラー
    DESCRIPTION: String,    // 警告 / エラーの理由、成功時は空
    RESULT: Object              // クライアントの要求するデータ、警告 / エラー時は空
}
```
- エラー: 処理の継続が不可能な場合 (サーバ内部でメモリ不足とか、ありえない状態に陥ったなど)
- 警告: 状況次第で処理の継続が可能な場合 (ユーザに正しいデータを入力し直してもらうなど)

クライアントでは、

```
if (response.STATUS_CODE) {
    alert(response.DESCRIPTION);

    if (response.STATUS_CODE > 1023) {
        exit;
    }
}
```

みたいなコードで対応する、と。

**Comment by launcelot777** [comment]
例えば、ERROR:12345　みたいな感じで画面に出して、ユーザから電話で問い合わせがあった時に、エラー番号を聞いて、一桁目が１だから通信エラーだ、とかDB系エラーだ、とか、すぐ対応できるといいと思います。
どんなエラーが考えられるか、ある程度でそろってから決めるというのはどうでしょうか。

**Comment by sarunokoshikake0831** [comment]
はい、了解です。
とりあえず open したままにしておきます。
きちんと決まってから close ですかね。

**Comment by sarunokoshikake0831** [comment]
検討の結果を Wiki に反映しておきます。
