### ISSUE TITLE
account, code, name, ID について

### ISSUE THREAD

**Issue by launcelot777** [Netkoubou/alice#5]
一度伺ったとは思うのですが、すぐ勘違いしてしまうので一度ISSUESに載せます。
違っていたところがあったら指摘してください。
・ID と code は同じもの。 
・name と account は同じもの。
・どちらもユーザごとにユニーク。
・ログインするときに使うのは、 account （と passphrase）

であっていますか？

**Comment by sarunokoshikake0831** [comment]
はい、合ってます。
ただ、入力では account で、出力は name ってのも何か変ですね。。。

他の項目 (部門診療科とか品目など) と合わせるために name と code にしていますが、
そうするのであれば、authenticateUser の入力も

```
{
    name: String,
    passphrase: String
}
```

とした方が混乱がなくて良いでしょうか?

**Comment by sarunokoshikake0831** [comment]
よくよく考えると、サーバからユーザの code と name をもらう必要がない気がしてきました。
もう少し仕様を詰めてみます。
その上でまた相談させて下さい。

**Comment by launcelot777** [comment]
了解です。
DBのカラム名とAPIで、同じ意味合いで違う名前のものが多くあるように見受けられます。
一度、ミーティングで文言の統一について話し合ってみましょうか。
category と item などもそうです。（個人的には、account, id, category がしっくりきます。）
あと、APIに goods とありますが、これは product と同意でしょうか。
また、これは細かいですが・・・
registerOrder で code とありますが、いろんなコードがあるので、product_code のほうがしっくりくるかもしれません。

**Comment by sarunokoshikake0831** [comment]
検討の結果を Wiki に反映しました。
